name: CI Pipeline

# Controls when the action will run: on push to the main branch or pull requests
on:
  push:
    branches:
      - dev
  pull_request:
    branches:
      - dev

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Build with Maven
        run: mvn clean install -DskipTests -Dspring-boot.run.profiles=none

  test:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Run tests and generate coverage report
        run: mvn test jacoco:report -DskipIntegrationTests=true

      - name: Upload coverage report
        uses: actions/upload-artifact@v3
        with:
          name: jacoco-report
          path: custom-coverage-report  # Update this path if necessary

  coverage:
    runs-on: ubuntu-latest
    needs: test

    steps:
      - name: Download JaCoCo report
        uses: actions/download-artifact@v3
        with:
          name: jacoco-report
          path: jacoco-report

      - name: Upload Coverage to Codecov
        uses: codecov/codecov-action@v3
        with:
          files: jacoco-report/jacoco.xml
          fail_ci_if_error: true  # This fails the job if coverage upload fails        fail_ci_if_error: true  # This fails the job if coverage upload fails