name: CI Pipeline

on:
  push:
    branches:
      - dev
  pull_request:
    branches:
      - dev

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Build with Maven
        run: mvn clean install -DskipTests -Dspring-boot.run.profiles=none

  test:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Run tests and generate coverage report
        run: mvn test jacoco:report -DskipIntegrationTests=true

      - name: Upload coverage report
        uses: actions/upload-artifact@v3
        with:
          name: jacoco-report
          path: target/site/jacoco

  update-repo-with-report:
    runs-on: ubuntu-latest
    needs: test

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Download JaCoCo report
        uses: actions/download-artifact@v3
        with:
          name: jacoco-report
          path: jacoco-report

      - name: Create directory for coverage report
        run: |
          mkdir -p coverage-reports
          cp -r jacoco-report/* coverage-reports/

      - name: Commit and push coverage report
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "actions@github.com"
          git add coverage-reports/
          git commit -m "Add JaCoCo coverage report" || echo "No changes to commit"
          git push